In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('city_ranking.csv')
df.head()

,city,country,Employment Score,Startup Score,Tourism Score,Housing Score,Food Ranking,Transport Score,Health Rank,Internet Speed Score,University Score,Access to Contraceptive Score,Gender Equality Score,Immigration Tolerence,Personal Freedom and Choice,LGBT friendly Score,Nightlife Score,Beer Ranking,Festival Ranking,Total
0,Berlin,Germany,4.8,9.0,6.2,5.2,7.2,7.1,3.9,5.0,4.9,6.9,7.5,8.4,7.8,9.7,10.0,7.0,8.0,7.14
1,Montréal,Canada,6.0,8.1,5.7,6.4,5.1,3.6,7.4,5.1,5.8,8.6,7.0,9.9,8.1,9.6,8.8,5.1,9.0,7.10
2,London,United Kingdom,6.6,9.8,9.8,0.5,2.2,7.2,4.4,4.7,10.0,9.5,7.1,8.7,9.6,9.4,9.4,2.5,7.5,6.71
3,Amsterdam,Netherlands,7.6,8.3,8.7,0.6,1.7,5.7,6.9,4.5,5.0,7.9,5.5,8.5,10.0,9.9,8.6,4.8,9.7,6.63
4,Toronto,Canada,6.3,9.5,4.4,2.7,6.1,4.3,7.4,7.1,5.2,8.6,7.0,9.9,9.4,9.8,4.5,3.6,9.4,6.60

In [5]:
categoryTable = df.set_index(df['city']).drop('city',1).drop('Total',1).drop('country',1)
categoryTable

,Employment Score,Startup Score,Tourism Score,Housing Score,Food Ranking,Transport Score,Health Rank,Internet Speed Score,University Score,Access to Contraceptive Score,Gender Equality Score,Immigration Tolerence,Personal Freedom and Choice,LGBT friendly Score,Nightlife Score,Beer Ranking,Festival Ranking
city,,,,,,,,,,,,,,,,,
Berlin,4.8,9.0,6.2,5.2,7.2,7.1,3.9,5.0,4.9,6.9,7.5,8.4,7.8,9.7,10.0,7.0,8.0
Montréal,6.0,8.1,5.7,6.4,5.1,3.6,7.4,5.1,5.8,8.6,7.0,9.9,8.1,9.6,8.8,5.1,9.0
London,6.6,9.8,9.8,0.5,2.2,7.2,4.4,4.7,10.0,9.5,7.1,8.7,9.6,9.4,9.4,2.5,7.5
Amsterdam,7.6,8.3,8.7,0.6,1.7,5.7,6.9,4.5,5.0,7.9,5.5,8.5,10.0,9.9,8.6,4.8,9.7
Toronto,6.3,9.5,4.4,2.7,6.1,4.3,7.4,7.1,5.2,8.6,7.0,9.9,9.4,9.8,4.5,3.6,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bern,1.3,0.3,7.3,2.4,0.2,2.8,9.6,9.4,1.0,8.0,6.3,7.2,8.7,6.0,2.8,1.3,0.0
Jerusalem,7.9,2.0,4.3,4.7,3.5,0.0,9.1,4.3,1.0,4.2,4.7,1.5,1.8,2.6,4.0,0.3,0.7
Brugge,1.7,0.0,3.4,6.1,0.5,1.1,3.5,8.2,1.0,8.9,5.6,7.4,6.1,4.7,0.7,4.8,0.7
Geneva,0.4,3.9,5.0,0.7,0.1,3.8,9.6,9.4,1.0,8.0,6.3,7.2,8.7,4.3,1.7,0.9,0.7
Bologna,5.8,1.4,3.2,5.1,1.7,1.1,9.1,4.6,1.0,3.4,3.3,6.2,0.8,2.0,0.9,2.3,2.8

In [6]:
fetures=categoryTable.columns
len(fetures)

17

In [7]:
user_pref=[]
print("give the ratiing: ")
for i in fetures:
    print(i+ ":")
    user_pref.append(float(input()))
    
user_pref

give the ratiing:
Employment Score:
6
Startup Score:
4.8
Tourism Score:
9
Housing Score:
5
Food Ranking:
7
Transport Score:
6
Health Rank:
8
Internet Speed Score:
4
University Score:
6
Access to Contraceptive Score:
8
Gender Equality Score:
5
Immigration Tolerence:
6
Personal Freedom and Choice:
9
LGBT friendly Score:
10
Nightlife Score:
10
Beer Ranking:
9
Festival Ranking:
9

[6.0,
 4.8,
 9.0,
 5.0,
 7.0,
 6.0,
 8.0,
 4.0,
 6.0,
 8.0,
 5.0,
 6.0,
 9.0,
 10.0,
 10.0,
 9.0,
 9.0]

In [8]:
user_pref1=pd.DataFrame([user_pref],columns=fetures)
userProfile = user_pref1.transpose()
userProfile

                                  0
Employment Score                6.0
Startup Score                   4.8
Tourism Score                   9.0
Housing Score                   5.0
Food Ranking                    7.0
Transport Score                 6.0
Health Rank                     8.0
Internet Speed Score            4.0
University Score                6.0
Access to Contraceptive Score   8.0
Gender Equality Score           5.0
Immigration Tolerence           6.0
Personal Freedom and Choice     9.0
LGBT friendly Score            10.0
Nightlife Score                10.0
Beer Ranking                    9.0
Festival Ranking                9.0

In [9]:
userProfile=userProfile.sum(axis=1)
userProfile

Employment Score                  6.0
Startup Score                     4.8
Tourism Score                     9.0
Housing Score                     5.0
Food Ranking                      7.0
Transport Score                   6.0
Health Rank                       8.0
Internet Speed Score              4.0
University Score                  6.0
Access to Contraceptive Score     8.0
Gender Equality Score             5.0
Immigration Tolerence             6.0
Personal Freedom and Choice       9.0
LGBT friendly Score              10.0
Nightlife Score                  10.0
Beer Ranking                      9.0
Festival Ranking                  9.0
dtype: float64

In [10]:
recommendationTable_df = ((categoryTable*userProfile).sum(axis=1))/(userProfile.sum())
recommendationTable_df.head()

city
Berlin       7.165025
Montréal     7.199343
London       7.208867
Amsterdam    7.087356
Toronto      6.827586
dtype: float64

In [11]:
recommendationTable_df=recommendationTable_df.sort_values(ascending=False)
recommendationTable_df

city
London       7.208867
Montréal     7.199343
Berlin       7.165025
Amsterdam    7.087356
Paris        6.850903
               ...
Bucharest    3.688834
Cape Town    3.680952
Lima         3.613629
Jerusalem    3.259442
Bologna      3.074877
Length: 110, dtype: float64

In [36]:
recommendationTable_df=pd.DataFrame(recommendationTable_df,columns=['score'])

In [37]:
recommendationTable_df.reset_index(inplace=True)

In [41]:
mergedf=pd.merge(df,recommendationTable_df,on='city')

In [42]:
recommendation_user =mergedf.sort_values('score',ascending=False)
recommendation_user.head(10)

,city,country,Employment Score,Startup Score,Tourism Score,Housing Score,Food Ranking,Transport Score,Health Rank,Internet Speed Score,...,Access to Contraceptive Score,Gender Equality Score,Immigration Tolerence,Personal Freedom and Choice,LGBT friendly Score,Nightlife Score,Beer Ranking,Festival Ranking,Total,score
2,London,United Kingdom,6.6,9.8,9.8,0.5,2.2,7.2,4.4,4.7,...,9.5,7.1,8.7,9.6,9.4,9.4,2.5,7.5,6.71,7.208867
1,Montréal,Canada,6.0,8.1,5.7,6.4,5.1,3.6,7.4,5.1,...,8.6,7.0,9.9,8.1,9.6,8.8,5.1,9.0,7.10,7.199343
0,Berlin,Germany,4.8,9.0,6.2,5.2,7.2,7.1,3.9,5.0,...,6.9,7.5,8.4,7.8,9.7,10.0,7.0,8.0,7.14,7.165025
3,Amsterdam,Netherlands,7.6,8.3,8.7,0.6,1.7,5.7,6.9,4.5,...,7.9,5.5,8.5,10.0,9.9,8.6,4.8,9.7,6.63,7.087356
14,Paris,France,4.5,9.3,9.7,1.3,0.8,8.5,8.3,2.0,...,9.4,7.5,7.2,5.2,8.3,9.9,0.7,9.8,5.98,6.850903
4,Toronto,Canada,6.3,9.5,4.4,2.7,6.1,4.3,7.4,7.1,...,8.6,7.0,9.9,9.4,9.8,4.5,3.6,9.4,6.60,6.827586
6,Barcelona,Spain,2.9,7.8,8.6,3.5,6.5,5.0,7.9,4.4,...,6.6,5.9,8.8,4.2,8.5,8.4,7.5,9.6,6.31,6.800000
7,New York City,USA,7.9,10.0,9.4,0.1,0.6,8.0,1.9,7.4,...,7.8,4.5,8.5,5.5,8.6,8.9,2.8,9.4,6.25,6.527915
19,Madrid,Spain,0.2,7.1,6.0,4.3,6.1,7.7,7.9,9.1,...,6.6,5.9,8.8,2.8,10.0,8.7,7.0,6.0,5.82,6.461248
5,Vancouver,Canada,8.5,8.7,2.5,1.5,5.3,2.4,7.4,6.1,...,8.6,7.0,9.9,9.7,9.3,3.2,5.1,8.3,6.34,6.441379